Repository nmfs-ost/ss3-doc, pull requests merged in 2023-10, with the labels that each got.

#190 Fix issue #189
  8data.tex
  _data_weighting.tex
Labels: documentation, Manual

#194 Fix ALK section to say it is disabled
  6starter.tex
Labels: documentation

#196 add changes issue #185
  8data.tex
Labels: documentation, Manual, 3.30.22 release

#198 Change ss to ss3 in doc; also change gender to sex in tutorial
  .github/workflows/deploy-ss3-docs.yml
  10optional_inputs.tex
  12runningSS3.tex
  13output.tex
  14r4ss.tex
  15special.tex
  1_4sections.tex
  5converting.tex
  6starter.tex
  7forecast.tex
  8data.tex
  9control.tex
  README.md
  SS3.bib
  SS330_User_Manual.tex
  User_Guides/getting_started/Getting_Started_SS3.Rmd
  User_Guides/model_step_by_step/model_tutorial.Rmd
  User_Guides/ss3_model_tips/ss3_model_tips.Rmd
  _data_weighting.tex
  _f_mortality.tex
  _forecast_module.tex
  docs/index.md
  tv_parameter_description.tex
Labels: documentation, Manual, User Guides, 3.30.22 release

#197 add note about retention required for part = 2
  8data.tex
Labels: documentation, 3.30.22 release
