Repository nmfs-ost/ss3-doc, pull requests merged in 2023-09, with the labels that each got.

#183 add hyperlinks to pg 26
  6starter.tex
  7forecast.tex
  8data.tex
  9control.tex
  _f_mortality.tex
Labels: documentation, Manual

#186 Fix typo in Linf equation
  9control.tex
Labels: Manual, User Guides

#193 A2 description fix
  9control.tex
Labels: documentation, Manual, User Guides
