Repository nmfs-ost/ss3-doc, pull requests merged in 2024-10, with the labels that each got.

#258 improve description of hermaphroditism
  9control.tex
  dictionary.txt
Labels: documentation, Manual

#257 Fix nav bar to go to new website rather than previous one
  html_usermanual_snippets.html
Labels: website

#256 Add clarification about bycatch in forecast
  7forecast.tex
  dictionary.txt
Labels: Manual
